apiVersion: v1
kind: Service
metadata:
  name: lyrist
  labels:
    app: lyrist
  namespace: lyrist
spec:
  selector:
    app: lyrist
  ports:
    - name: tcp3000
      port: 3000
      protocol: TCP
      targetPort: 3000
  sessionAffinity: None
  type: ClusterIP